### PR TITLE
Form fixed. ESLint and Prettier plugins configuration added

### PR DESCRIPTION
**Pull request by DavZeus**
# Animated label on focus
akU0Fc4bHls
# "Thankyou" div after form submission 
zkGJAuYToEY

### CODE REVIEW

**Comment by lArtiquel** [comment]
Great! Thank you! U r amazing! We love you!

**Comment by lArtiquel** [comment]
Changes pushed into master. Another dude asked me to merge, cuz he wants to make some contribution based on that changes.

**Comment by DavZeus** [comment]
Thanks maaan

**Comment by Alegrix** [comment]
Good job man)

**Pull request merged**
